=== Ahil-Kanna/Sports-Updates/result.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="match" >  
  <xs:complexType>  
        <xs:sequence>
        	<xs:element name="tournament" type="xs:string"/>
        	<xs:element name="team1">
        		<xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:pattern value="[A-Z][A-Z][A-Z]"></xs:pattern>
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        	<xs:element name="team2">
        		<xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:pattern value="[A-Z][A-Z][A-Z]"></xs:pattern>
        			
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        	<xs:element name="score1" type="xs:integer"></xs:element>
        	<xs:element name="score2" type="xs:integer"></xs:element>
        	<xs:element name="flag1">
        		<xs:simpleType>
        			<xs:restriction base="xs:anyURI">
        				<xs:pattern value="https://.+"></xs:pattern>
        			
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        	<xs:element name="flag2">
        		<xs:simpleType>
        			<xs:restriction base="xs:anyURI">
        				<xs:pattern value="https://.+"></xs:pattern>
        			
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        	<xs:element name="status">
        		<xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:enumeration value="closed"></xs:enumeration>
        				<xs:enumeration value="open"></xs:enumeration>
        				<xs:enumeration value="not_started"></xs:enumeration>
        			
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:element>
        
        </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Ahil-Kanna/Sports-Updates/Result.xml
<?xml version="1.0" encoding="UTF-8"?>
<match xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="result.xsd">
    <tournament>Asian Games</tournament>
    <team1>SYR</team1>
    <team2>VNM</team2>
    <score1>0</score1>
    <score2>1</score2>
    <flag1>https://restcountries.eu/data/syr.svg</flag1>
    <flag2>https://restcountries.eu/data/vnm.svg</flag2>
    <status>closed</status>
</match>
